# Site
title:              "Arda C. Tugay"
bio:                "Software Engineer"
description:        "Moon is a minimal, one column jekyll theme for your blog."
reading_time:       true
words_per_minute:   200
logo:               'assets/img/logo.png'
#background:         'assets/img/placeholder-big.jpg'
tiled_bg:           false   # Set this true if you want to tile your background image, otherwise it will be covered
locale:             en_US
url:                https://tugayac.github.io
collections:
  projects:
    output: true
    permalink: /projects/:title/
  skills:
    output: false

# Jekyll
permalink:          /:title/
markdown:           kramdown
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
# sass:
#   sass_dir:         _sass
#   style:            compressed

assets:
  # compress: # Compresses for production by default
  #   css: true
  #   js: true
  sources:
    - "assets/js"
    - "assets/css"
    - "assets/fonts"
    - "assets/img"
  autoprefixer:
    browsers:
      - "iOS >= 10"
      - "last 3 Edge versions"
      - "last 5 Chrome versions"
      - "last 5 ChromeAndroid versions"
      - "last 5 Firefox versions"
      - "Safari >= 10"

# Comments
disqus_shortname:   ardactugay

# Social
# if you don't have any of social below, comment the line.
#google:
  #analytics:
  #verify:
  #ad-client:
  #ad-slot:
#bing-verify:
email:             ardactugay@gmail.com
#twitter:            username
#facebook:           username
github-url:        tugayac
stackoverflow:     4548148/ardatr   from a "http://stackoverflow.com/users/123456/username" link
linkedin:          arda-tugay-09b22861
#instagram:          username
#medium:            '@username'
#youtube:           username
#youtube-channel:   channel
#codepen:           username

# Gems
plugins:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-assets

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
